config/routes.rb
Rails.application.routes.draw do
  resources :products, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forms/product.rb
class Forms::Product < Product
  REGISTRABLE_ATTRIBUTES = %i(register code name price)
  attr_accessor :register
end

app/models/product.rb
class Product < ApplicationRecord
  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product_registration_form = ProductRegistrationForm.new
  end

  def create
    @product_registration_form = ProductRegistrationForm.new(product_registration_form_params)

    if @product_registration_form.save
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def product_registration_form_params
    params
      .require(:product_registration_form)
        .permit( products_attributes: Forms::Product::REGISTRABLE_ATTRIBUTES)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title>FormObjectPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%= link_to '新規作成', new_product_path, class:'btn btn-primary' %>
<div class="overflow-x-auto">
  <table class="table w-full">
    <thead>
      <tr>
        <th>ID</th>
        <th>商品コード</th>
        <th>商品名</th>
        <th>販売価格</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.code %></td>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<%= link_to '戻る', products_path, class:'btn' %>
<%= form_with model: @product_registration_form, url: products_path do |f| %>
  <%= render 'shared/error_message', object: f.object %>
  <table class="table">
    <thead>
      <tr>
        <th>登録</th>
        <th>商品コード</th>
        <th>商品名</th>
        <th>価格</th>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :products do |ff| %>
        <tr>
          <td>
            <%= ff.check_box :register %>
          </td>
          <td>
            <%= ff.text_field :code %>
          </td>
          <td>
            <%= ff.text_field :name %>
          </td>
          <td>
            <%= ff.text_field :price %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= f.submit '一括登録', class:'btn btn-primary' %>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_messages">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>